language: julia
jobs:
  include:
    - stage: "Documentation"
      julia: nightly
      os: linux
      script:
        - julia --project=docs/ -e 'using Pkg; Pkg.instantiate();
                                    Pkg.develop(PackageSpec(path=pwd()))'
        - julia --project=docs/ docs/make.jl
      after_success: skip
      install:
        - sudo pip install --upgrade pip
        - sudo pip install matplotlib
