site_name:           Discuit.jl
repo_url:            https://github.com/mjb3/Discuit.jl
site_description:    Fast parameter inference for discrete state space continuous time (DSSCT) models in Julia.
site_author:         Martin Burke
theme:               cyborg
# theme:               bootstrap386

markdown_extensions:
  - codehilite
  - extra
  - tables
  - fenced_code
  - mdx_math # For LaTeX

extra_css:
  - assets/Documenter.css

extra_javascript:
  - https://cdn.mathjax.org/mathjax/latest/MathJax.js?config=TeX-AMS_HTML
  - assets/mathjaxhelper.js
  - https://cdn.rawgit.com/pcooksey/bibtex-js/ef59e62c/src/bibtex_js.js

docs_dir: 'build'

pages:
- Introduction: index.md
- Examples: examples.md
- Models: models.md
- Manual: manual.md
