site_name:           Discuit.jl
repo_url:            https://github.com/mjb3/Discuit.jl
site_description:    Description
site_author:         Martin
theme:               cyborg
# theme:               bootstrap386

markdown_extensions:
  - codehilite
  - extra
  - tables
  - fenced_code
  - mdx_bib:
    - bibtex_file: 'discuit.bib'
    - order: 'unsorted'
  # - mdx_math # For LaTeX

extra_css:
  - assets/Documenter.css

extra_javascript:
  - https://cdn.mathjax.org/mathjax/latest/MathJax.js?config=TeX-AMS_HTML
  - assets/mathjaxhelper.js

docs_dir: 'build'

pages:
- Introduction: index.md
- Examples: examples.md
- Models: models.md
- Manual: manual.md
